apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: helloworld.tomas.website
spec:
  secretName: helloworld.tomas.website
  dnsNames:
  - helloworld.tomas.website
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
